"""Adicionar Itens ao pedido

Revision ID: 3efea7e9a39a
Revises: 5c085b33e8bf
Create Date: 2025-07-29 11:41:50.752613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efea7e9a39a'
down_revision: Union[str, Sequence[str], None] = '5c085b33e8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
